# Generated by Django 3.2.5 on 2022-01-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookTime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepTime',
            field=models.DurationField(),
        ),
    ]
