# Generated by Django 4.0.1 on 2022-01-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220106_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cookTime',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepTime',
            new_name='prep_time',
        ),
    ]
